[package]
name = "hypersquare"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2.33.3"
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
pickledb = "0.4.1"
